### ISSUE TITLE
不能播放？

### ISSUE THREAD

**Issue by uintvalue** [skyline75489/pyfm#13]
sudo apt-get install mpg123 安装了mpg123，
sudo pip install pyfm 安装了pyfm，
/$ pyfm config 配置账号密码也问题
/$ pyfm
能够正常出现电台选择的页面，可以上下移动光标，但按回车选中播放的时候就弹出下面的信息：

Traceback (most recent call last):
  File "/usr/local/bin/pyfm", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pyfm/fm.py", line 357, in main
    fm.start()
  File "/usr/local/lib/python2.7/dist-packages/pyfm/fm.py", line 352, in start
    self.main_loop.run()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/local/lib/python2.7/dist-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/local/lib/python2.7/dist-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/local/lib/python2.7/dist-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/local/lib/python2.7/dist-packages/urwid/decoration.py", line 621, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/usr/local/lib/python2.7/dist-packages/pyfm/ui.py", line 38, in keypress
    return super(ChannelListBox, self).keypress(size, key)
  File "/usr/local/lib/python2.7/dist-packages/urwid/listbox.py", line 987, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/usr/local/lib/python2.7/dist-packages/urwid/wimp.py", line 535, in keypress
    self._emit('click')
  File "/usr/local/lib/python2.7/dist-packages/urwid/widget.py", line 464, in _emit
    signals.emit_signal(self, name, self, _args)
  File "/usr/local/lib/python2.7/dist-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/local/lib/python2.7/dist-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(_args_to_pass))
  File "/usr/local/lib/python2.7/dist-packages/pyfm/fm.py", line 329, in on_channel_chosen
    self._play_track()
  File "/usr/local/lib/python2.7/dist-packages/pyfm/fm.py", line 189, in _play_track
    self.current_song.album_title, appIcon=self.current_song.picture, open_URL=self.current_song.album)
  File "/usr/local/lib/python2.7/dist-packages/pyfm/notifier.py", line 112, in _notify_send_notify
    stderr=subprocess.STDOUT
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] 没有那个文件或目录

**Comment by skyline75489** [comment]
貌似是 notifier 的问题，可以通过设置把允许通知关掉试试

**Comment by uintvalue** [comment]
按你说的确实解决了，不过不管选哪个台，播放的都是同一首歌。。。。然后歌名、描述就成了下面这样：

  • 民谣                    豆瓣FM - 客户端已经停止使用，请前往 douban.fm 收听，感谢理解。

**Comment by skyline75489** [comment]
我去，看来豆瓣是把接口给封锁了啊。

可以看看这个项目，貌似通过输入验证码还可以用 https://github.com/taizilongxu/douban.fm

**Comment by uintvalue** [comment]
这个我今天也用了，大多数电台都没有了，我这里只显示红心电台、私人兆赫和豆瓣精选。

**Comment by skyline75489** [comment]
那看来就是豆瓣把接口给限制了，本来这个接口也是前人抓包抓出来的，没办法保证可用性。

**Comment by uintvalue** [comment]
o(╯□╰)o，命不好，刚用上就被限制了。。。
